import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';

const oxDefaultEmoji = [
  Emoji('😀', 'Grinning Face'),
  Emoji('😃', 'Grinning Face With Big Eyes'),
  Emoji('😄', 'Grinning Face With Smiling Eyes'),
  Emoji('😁', 'Beaming Face With Smiling Eyes'),
  Emoji('😆', 'Grinning Squinting Face'),
  Emoji('😅', 'Grinning Face With Sweat'),
  Emoji('🤣', 'Rolling on the Floor Laughing'),
  Emoji('😂', 'Face With Tears of Joy'),
  Emoji('🙂', 'Slightly Smiling Face'),
  Emoji('🙃', 'Upside-Down Face'),
  Emoji('😉', 'Winking Face'),
  Emoji('🔥', 'Fire'),
  Emoji('🚀', 'Rocket'),
  Emoji('💯', '100 percent'),
  Emoji('⚡️', 'Lightning'),
  Emoji('❤️', 'Love'),
  Emoji('🎉', 'Congratulation'),
  Emoji('🎯', 'Goal'),
  Emoji('😊', 'Smiling Face With Smiling Eyes'),
  Emoji('😇', 'Smiling Face With Halo'),
  Emoji('🥰', 'Smiling Face With Hearts'),
  Emoji('😍', 'Smiling Face With Heart-Eyes'),
  Emoji('🤩', 'Star-Struck'),
  Emoji('😘', 'Face Blowing a Kiss'),
  Emoji('😗', 'Kissing Face'),
  Emoji('☺', 'Smiling Face'),
  Emoji('😚', 'Kissing Face With Closed Eyes'),
  Emoji('😙', 'Kissing Face With Smiling Eyes'),
  Emoji('😋', 'Face Savoring Food'),
  Emoji('😛', 'Face With Tongue'),
  Emoji('😜', 'Winking Face With Tongue'),
  Emoji('🤪', 'Zany Face'),
  Emoji('😝', 'Squinting Face With Tongue'),
  Emoji('🤑', 'Money-Mouth Face'),
  Emoji('🤗', 'Hugging Face'),
  Emoji('🫣', 'Face with Peeking Eye'),
  Emoji('🤭', 'Face With Hand Over Mouth'),
  Emoji('🫢', 'Face with Open Eyes and Hand Over Mouth'),
  Emoji('🫡', 'Saluting Face'),
  Emoji('🤫', 'Shushing Face'),
  Emoji('🫠', 'Melting Face'),
  Emoji('🤔', 'Thinking Face'),
  Emoji('🤐', 'Zipper-Mouth Face'),
  Emoji('🤨', 'Face With Raised Eyebrow'),
  Emoji('😐', 'Neutral Face'),
  Emoji('🫤', 'Face with Diagonal Mouth'),
  Emoji('😑', 'Expressionless Face'),
  Emoji('😶', 'Face Without Mouth'),
  Emoji('🫥', 'Dotted Line Face'),
  Emoji('😏', 'Smirking Face'),
  Emoji('😒', 'Unamused Face'),
  Emoji('🙄', 'Face With Rolling Eyes'),
  Emoji('😬', 'Grimacing Face'),
  Emoji('🤥', 'Lying Face'),
  Emoji('😌', 'Relieved Face'),
  Emoji('😔', 'Pensive Face'),
  Emoji('🥹', 'Face Holding Back Tears'),
  Emoji('😪', 'Sleepy Face'),
  Emoji('🤤', 'Drooling Face'),
  Emoji('😴', 'Sleeping Face'),
  Emoji('😷', 'Face With Medical Mask'),
  Emoji('🤒', 'Face With Thermometer'),
  Emoji('🤕', 'Face With Head-Bandage'),
  Emoji('🤢', 'Nauseated Face'),
  Emoji('🤮', 'Face Vomiting'),
  Emoji('🤧', 'Sneezing Face'),
  Emoji('🥵', 'Hot Face'),
  Emoji('🥶', 'Cold Face'),
  Emoji('🥴', 'Woozy Face'),
  Emoji('😵', 'Dizzy Face'),
  Emoji('🤯', 'Exploding Head'),
  Emoji('🤠', 'Cowboy Hat Face'),
  Emoji('🥳', 'Partying Face'),
  Emoji('😎', 'Smiling Face With Sunglasses'),
  Emoji('🤓', 'Nerd Face'),
  Emoji('🧐', 'Face With Monocle'),
  Emoji('😕', 'Confused Face'),
  Emoji('😟', 'Worried Face'),
  Emoji('🙁', 'Slightly Frowning Face'),
  Emoji('☹', 'Frowning Face'),
  Emoji('😮', 'Face With Open Mouth'),
  Emoji('😯', 'Hushed Face'),
  Emoji('😲', 'Astonished Face'),
  Emoji('😳', 'Flushed Face'),
  Emoji('🥺', 'Pleading Face'),
  Emoji('😦', 'Frowning Face With Open Mouth'),
  Emoji('😧', 'Anguished Face'),
  Emoji('😨', 'Fearful Face'),
  Emoji('😰', 'Anxious Face With Sweat'),
  Emoji('😥', 'Sad but Relieved Face'),
  Emoji('😢', 'Crying Face'),
  Emoji('😭', 'Loudly Crying Face'),
  Emoji('😱', 'Face Screaming in Fear'),
  Emoji('😖', 'Confounded Face'),
  Emoji('😣', 'Persevering Face'),
  Emoji('😞', 'Disappointed Face'),
  Emoji('😓', 'Downcast Face With Sweat'),
  Emoji('😩', 'Weary Face'),
  Emoji('😫', 'Tired Face'),
  Emoji('😤', 'Face With Steam From Nose'),
  Emoji('😡', 'Pouting Face'),
  Emoji('😠', 'Angry Face'),
  Emoji('🤬', 'Face With Symbols on Mouth'),
  Emoji('😈', 'Smiling Face With Horns'),
  Emoji('👿', 'Angry Face With Horns'),
  Emoji('💀', 'Skull'),
  Emoji('☠', 'Skull and Crossbones'),
  Emoji('💩', 'Pile of Poo'),
  Emoji('🤡', 'Clown Face'),
  Emoji('👹', 'Ogre'),
  Emoji('👺', 'Goblin'),
  Emoji('👻', 'Ghost'),
  Emoji('👽', 'Alien'),
  Emoji('👾', 'Alien Monster'),
  Emoji('🤖', 'Robot Face'),
  Emoji('😺', 'Grinning Cat Face'),
  Emoji('😸', 'Grinning Cat Face With Smiling Eyes'),
  Emoji('😹', 'Cat Face With Tears of Joy'),
  Emoji('😻', 'Smiling Cat Face With Heart-Eyes'),
  Emoji('😼', 'Cat Face With Wry Smile'),
  Emoji('😽', 'Kissing Cat Face'),
  Emoji('🙀', 'Weary Cat Face'),
  Emoji('😿', 'Crying Cat Face'),
  Emoji('😾', 'Pouting Cat Face'),
  Emoji('🫶', 'Heart Hands', hasSkinTone: true),
  Emoji('👋', 'Waving Hand', hasSkinTone: true),
  Emoji('🤚', 'Raised Back of Hand', hasSkinTone: true),
  Emoji('🖐', 'Hand With Fingers Splayed', hasSkinTone: true),
  Emoji('✋', 'Raised Hand', hasSkinTone: true),
  Emoji('🖖', 'Vulcan Salute', hasSkinTone: true),
  Emoji('👌', 'OK Hand', hasSkinTone: true),
  Emoji('🤌', 'Pinched Fingers', hasSkinTone: true),
  Emoji('🤏', 'Pinching Hand', hasSkinTone: true),
  Emoji('🫳', 'Palm Down Hand', hasSkinTone: true),
  Emoji('🫴', 'Palm Up Hand', hasSkinTone: true),
  Emoji('✌️', 'Victory Hand', hasSkinTone: true),
  Emoji('🫰', 'Hand with Index Finger and Thumb Crossed', hasSkinTone: true),
  Emoji('🤞', 'Crossed Fingers', hasSkinTone: true),
  Emoji('🤟', 'Love-You Gesture', hasSkinTone: true),
  Emoji('🤘', 'Sign of the Horns', hasSkinTone: true),
  Emoji('🤙', 'Call Me Hand', hasSkinTone: true),
  Emoji('👈', 'Backhand Index Pointing Left', hasSkinTone: true),
  Emoji('👉', 'Backhand Index Pointing Right', hasSkinTone: true),
  Emoji('👆', 'Backhand Index Pointing Up', hasSkinTone: true),
  Emoji('🖕', 'Middle Finger', hasSkinTone: true),
  Emoji('👇', 'Backhand Index Pointing Down', hasSkinTone: true),
  Emoji('☝', 'Index Pointing Up', hasSkinTone: true),
  Emoji('👍', 'Thumbs Up', hasSkinTone: true),
  Emoji('👎', 'Thumbs Down', hasSkinTone: true),
  Emoji('✊', 'Raised Fist', hasSkinTone: true),
  Emoji('👊', 'Oncoming Fist', hasSkinTone: true),
  Emoji('🤛', 'Left-Facing Fist', hasSkinTone: true),
  Emoji('🤜', 'Right-Facing Fist', hasSkinTone: true),
  Emoji('🫲', 'Leftwards Hand', hasSkinTone: true),
  Emoji('🫱', 'Rightwards Hand', hasSkinTone: true),
  Emoji('👏', 'Clapping Hands', hasSkinTone: true),
  Emoji('🙌', 'Raising Hands', hasSkinTone: true),
  Emoji('👐', 'Open Hands', hasSkinTone: true),
  Emoji('🤲', 'Palms Up Together', hasSkinTone: true),
  Emoji('🤝', 'Handshake', hasSkinTone: true),
  Emoji('🙏', 'Folded Hands', hasSkinTone: true),
  Emoji('🫵', 'Index Pointing at the Viewer', hasSkinTone: true),
  Emoji('✍', 'Writing Hand', hasSkinTone: true),
  Emoji('💅', 'Nail Polish', hasSkinTone: true),
  Emoji('🤳', 'Selfie', hasSkinTone: true),
  Emoji('💪', 'Flexed Biceps', hasSkinTone: true),
  Emoji('🦵', 'Leg', hasSkinTone: true),
  Emoji('🦶', 'Foot', hasSkinTone: true),
  Emoji('👂', 'Ear', hasSkinTone: true),
  Emoji('👃', 'Nose', hasSkinTone: true),
  Emoji('🧠', 'Brain'),
  Emoji('🦴', 'Bone'),
  Emoji('👀', 'Eyes'),
  Emoji('👁', 'Eye'),
  Emoji('💋', 'Kiss Mark'),
  Emoji('👄', 'Mouth'),
  Emoji('🫦', 'Biting Lip'),
  Emoji('🦷', 'Tooth'),
  Emoji('👅', 'Tongue'),
];